apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo-service
  namespace: "yolomy"
  labels:
    #Project ID
    app: yolomy-mongo
spec:
  ports:
    - nodeport: 32425
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    name: yolomy-mongo
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolomy-mongo
  namespace: "yolomy"
  labels:
    app: yolomy-mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolomy-mongo
  template:
    metadata:
      labels:
        app: yolomy-mongo
    spec:
      containers:
        - name: yolomy-mongo
          image: noshmak/mongoauth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4
