apiVersion: v1
kind: Service
metadata:
  name: yolomy-mongo
  namespace: "yolomy"
  labels:
    #Project ID
    app: yolomy-mongo
spec:
  ports:
    - nodePort: 32425
      port: 27107
      targetPort: 27017
      protocol: TCP
  
  selector:
    app: yolomy-mongo
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolomy-mongo
  namespace: "yolomy"
  labels:
    app: yolomy-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolomy-mongo
  template:
    metadata:
      labels:
        app: yolomy-mongo
    spec:
      containers:
        - name: yolomy-mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4
