apiVersion: v1
kind: Service
metadata:
  name: yolomy-mongo
  namespace: "yolomy"
  labels:
    #Project ID
    app: yolomy-mongo
spec:
  ports:
    - nodePort: 32425
      port: 27107
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
  selector:
    app: yolomy-mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolomy-mongo
  namespace: "yolomy"
  labels:
    app: yolomy-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolomy-mongo
  template:
    metadata:
      labels:
        app: yolomy-mongo
    spec:
      containers:
        - name: yolomy-mongo
          image: noshmak/mongoauth:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
